#!/bin/sh

# IT IS MY TESTER TO KNOW HOW MANY MOVES YOU NEED TO SORT A RANDOM SET OF NUMBER.
# YOU CAN CHANGE THE NUMBER OF TEST IN THE FOR LINE, CURRENTLY 50
# YOU CAN CHANGE THE NUMBER OF NUMBER TO GENERATE IN AN ALLEATORY ORDER, CURRENTLY 100
# IF YOU DO NOT WANT TO SEE THE SET OF NUMBER PLEASE COMMENT LINE "echo SET OF NUMBERS TESTED: $ARG"
# TAKE OUT "| wc -l" IF YOU WANT TO SEE THE LIST OF MOVES.
# IF YOU WANT TO CHECK IF YOUR LIST OF MOVES SORT THE SET OF NUMBERS CHANGE "wc -l" TO "./checker $ARG". 

for i in {1. .50}
do
echo TEST NUMBER: $i
ARG=$(ruby -e "puts (1..100).to_a.shuffle.join(' ')")
echo SET OF NUMBERS TESTED: $ARG
echo -n "NUMBER OF MOVES: "
./push_swap $ARG | wc -l
#echo
done
